#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define CHUNK_SIZE 256
#define CHUNK_RENDER_DISTANCE CHUNK_SIZE * 4
#define HEIGHT_SCALE 50

#define NOISE_HEIGHT_SCALE 2.0f
#define NOISE_SPEED 0.6f

#define CAMERA_MOVEMENT_SPEED 30.0f
#define CAMERA_ROTATION_SPEED 1.0f
#define CAMERA_SPEEDUP_FACTOR 4.0f
#define CAMERA_ZOOM 1.0f